site_name: MIAPPE Wizard
repo_url: https://github.com/IPK-BIT/miappe-wizard.git
repo_name: miappe-wizard
nav:
  - Home: index.md
  - Configuration: configuration.md
theme:
  name: material
  logo: assets/logo.png
  favicon: assets/logo.png
  palette:
    primary: green
    accent: lime
  features:
    - navigation.sections
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - tables
  - admonition
  - pymdownx.details