site_name: ISA Wizard
repo_url: https://github.com/IPK-BIT/isa-wizard.git
repo_name: isa-wizard
nav:
  - Home: index.md
  - Administrator Guide: 
    - configuration/index.md
    - configuration/basic.md
    - configuration/steps.md
    - configuration/explanations.md
  - User Guide:
    - examples/index.md
  - Developer Guide:
    - developer/index.md
theme:
  name: material
  logo: assets/logo.png
  favicon: assets/logo.png
  palette:
    primary: green
    accent: lime
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.indexes
markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - tables
  - admonition
  - pymdownx.details