/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * JSON-schema representing an investigation in the ISA model
 */
export interface ISAInvestigationSchema {
	'@id'?: string;
	filename?: string;
	identifier?: string;
	title?: string;
	description?: string;
	submissionDate?: string;
	publicReleaseDate?: string;
	ontologySourceReferences?: ISAOntologySourceReferenceSchema[];
	publications?: ISAInvestigationSchema1[];
	people?: ISAPersonSchema[];
	studies?: StudyJSONSchema[];
	comments?: ISACommentSchemaItCorrespondsToISACommentConstruct[];
}
/**
 * JSON-schema representing an ontology reference in the ISA model
 */
export interface ISAOntologySourceReferenceSchema {
	comments?: ISACommentSchemaItCorrespondsToISACommentConstruct[];
	description?: string;
	file?: string;
	name?: string;
	version?: string;
}
/**
 * JSON-schema representing a comment in the ISA model
 */
export interface ISACommentSchemaItCorrespondsToISACommentConstruct {
	'@id'?: string;
	name?: string;
	value?: string;
}
/**
 * JSON-schema representing an investigation in the ISA model
 */
export interface ISAInvestigationSchema1 {
	comments?: ISACommentSchemaItCorrespondsToISACommentConstruct[];
	pubMedID?: string;
	doi?: string;
	authorList?: string;
	title?: string;
	status?: ISAOntologyReferenceSchema;
}
/**
 * JSON-schema representing an ontology reference or annotation in the ISA model (for fields that are required to be ontology annotations)
 */
export interface ISAOntologyReferenceSchema {
	'@id'?: string;
	annotationValue?: string | number;
	/**
	 * The abbreviated ontology name. It should correspond to one of the sources as specified in the ontologySourceReference section of the Investigation.
	 */
	termSource?: string;
	termAccession?: string;
	comments?: ISACommentSchemaItCorrespondsToISACommentConstruct[];
}
/**
 * JSON-schema representing a person in the ISA model
 */
export interface ISAPersonSchema {
	'@id'?: string;
	lastName?: string;
	firstName?: string;
	midInitials?: string;
	email?: string;
	phone?: string;
	fax?: string;
	address?: string;
	affiliation?: string;
	roles?: ISAOntologyReferenceSchema[];
	comments?: ISACommentSchemaItCorrespondsToISACommentConstruct[];
}
/**
 * JSON Schema describing an Study
 */
export interface StudyJSONSchema {
	'@id'?: string;
	filename?: string;
	identifier?: string;
	title?: string;
	description?: string;
	submissionDate?: string;
	publicReleaseDate?: string;
	publications?: ISAInvestigationSchema1[];
	people?: ISAPersonSchema[];
	studyDesignDescriptors?: ISAOntologyReferenceSchema[];
	protocols?: ISAProtocolSchema[];
	materials?: {
		sources?: ISASourceSchema[];
		samples?: ISASampleSchema[];
		otherMaterials?: ISAMaterialNodeSchema[];
		[k: string]: unknown;
	};
	processSequence?: ISAProcessOrProtocolApplicationSchemaCorrespondsToProtocolREFColumnsInTheStudyAndAssayFiles[];
	assays?: AssayJSONSchema[];
	factors?: ISAFactorSchema[];
	/**
	 * List of all the characteristics categories (or material attributes) defined in the study, used to avoid duplication of their declaration when each material_attribute_value is created.
	 */
	characteristicCategories?: ISAMaterialAttributeSchema1[];
	/**
	 * List of all the units defined in the study, used to avoid duplication of their declaration when each value is created.
	 */
	unitCategories?: ISAOntologyReferenceSchema[];
	comments?: ISACommentSchemaItCorrespondsToISACommentConstruct[];
}
/**
 * JSON-schema representing a protocol in the ISA model
 */
export interface ISAProtocolSchema {
	'@id'?: string;
	name?: string;
	protocolType?: ISAOntologyReferenceSchema;
	description?: string;
	uri?: string;
	version?: string;
	parameters?: ISAProtocolParameterSchema[];
	components?: {
		[k: string]: unknown;
	}[];
	comments?: ISACommentSchemaItCorrespondsToISACommentConstruct[];
}
/**
 * JSON-schema representing a parameter for a protocol (category declared in the investigation file) in the ISA model
 */
export interface ISAProtocolParameterSchema {
	'@id'?: string;
	parameterName?: ISAOntologyReferenceSchema;
	comments?: ISACommentSchemaItCorrespondsToISACommentConstruct[];
}
/**
 * JSON-schema representing a source in the ISA model. Sources are considered as the starting biological material used in a study.
 */
export interface ISASourceSchema {
	'@id'?: string;
	name?: string;
	characteristics?: ISAMaterialAttributeSchema[];
}
/**
 * JSON-schema representing a material attribute (or characteristic) value in the ISA model
 */
export interface ISAMaterialAttributeSchema {
	'@id'?: string;
	category?: ISAMaterialAttributeSchema1;
	value?: ISAOntologyReferenceSchema | string | number;
	unit?: ISAOntologyReferenceSchema;
}
/**
 * JSON-schema representing a characteristics category (what appears between the brackets in Charactersitics[]) in the ISA model
 */
export interface ISAMaterialAttributeSchema1 {
	'@id'?: string;
	characteristicType?: ISAOntologyReferenceSchema;
}
/**
 * JSON-schema representing a sample in the ISA model. A sample represents a major output resulting from a protocol application other than the special case outputs of Extract or a Labeled Extract.
 */
export interface ISASampleSchema {
	'@id'?: string;
	name?: string;
	characteristics?: ISAMaterialAttributeSchema[];
	factorValues?: ISAFactorValueSchema[];
	derivesFrom?: ISASourceSchema[];
}
/**
 * JSON-schema representing a factor value in the ISA model
 */
export interface ISAFactorValueSchema {
	'@id'?: string;
	category?: ISAFactorSchema;
	value?: ISAOntologyReferenceSchema | string | number;
	unit?: ISAOntologyReferenceSchema;
	comments?: ISACommentSchemaItCorrespondsToISACommentConstruct[];
}
/**
 * JSON-schema representing a factor value in the ISA model
 */
export interface ISAFactorSchema {
	'@id'?: string;
	factorName?: string;
	factorType?: ISAOntologyReferenceSchema;
	comments?: ISACommentSchemaItCorrespondsToISACommentConstruct[];
}
/**
 * JSON-schema representing a material node in the ISA model, which is not a source or a sample (as they have specific schemas) - this will correspond to 'Extract Name', 'Labeled Extract Name'
 */
export interface ISAMaterialNodeSchema {
	'@id'?: string;
	name?: string;
	type?: 'Extract Name' | 'Labeled Extract Name';
	characteristics?: ISAMaterialAttributeSchema[];
	derivesFrom?: ISAMaterialNodeSchema[];
	comments?: ISACommentSchemaItCorrespondsToISACommentConstruct[];
}
/**
 * JSON-schema representing a protocol application in the ISA model
 */
export interface ISAProcessOrProtocolApplicationSchemaCorrespondsToProtocolREFColumnsInTheStudyAndAssayFiles {
	'@id'?: string;
	name?: string;
	executesProtocol?: ISAProtocolSchema;
	parameterValues?: ISAProcessParameterValueSchema[];
	performer?: string;
	date?: string;
	previousProcess?: ISAProcessOrProtocolApplicationSchemaCorrespondsToProtocolREFColumnsInTheStudyAndAssayFiles;
	nextProcess?: ISAProcessOrProtocolApplicationSchemaCorrespondsToProtocolREFColumnsInTheStudyAndAssayFiles;
	inputs?: (ISASourceSchema | ISASampleSchema | ISADataSchema | ISAMaterialNodeSchema)[];
	outputs?: (ISASampleSchema | ISADataSchema | ISAMaterialNodeSchema)[];
	comments?: ISACommentSchemaItCorrespondsToISACommentConstruct[];
}
/**
 * JSON-schema representing a Parameter Value (associated with a Protocol REF) in the ISA model
 */
export interface ISAProcessParameterValueSchema {
	category?: ISAProtocolParameterSchema;
	value?: ISAOntologyReferenceSchema | string | number;
	unit?: ISAOntologyReferenceSchema;
}
/**
 * JSON-schema representing a data file in the ISA model
 */
export interface ISADataSchema {
	'@id'?: string;
	name?: string;
	type?:
		| 'Raw Data File'
		| 'Derived Data File'
		| 'Image File'
		| 'Acquisition Parameter Data File'
		| 'Derived Spectral Data File'
		| 'Protein Assignment File'
		| 'Raw Spectral Data File'
		| 'Peptide Assignment File'
		| 'Array Data File'
		| 'Derived Array Data File'
		| 'Post Translational Modification Assignment File'
		| 'Derived Array Data Matrix File'
		| 'Free Induction Decay Data File'
		| 'Metabolite Assignment File'
		| 'Array Data Matrix File';
	comments?: ISACommentSchemaItCorrespondsToISACommentConstruct[];
}
/**
 * JSON Schema describing an Assay
 */
export interface AssayJSONSchema {
	'@id'?: string;
	filename?: string;
	measurementType?: ISAOntologyReferenceSchema;
	technologyType?: ISAOntologyReferenceSchema;
	technologyPlatform?: string;
	dataFiles?: ISADataSchema[];
	materials?: {
		samples?: ISASampleSchema[];
		otherMaterials?: ISAMaterialNodeSchema[];
		[k: string]: unknown;
	};
	/**
	 * List of all the characteristics categories (or material attributes) defined in the study, used to avoid duplication of their declaration when each material_attribute_value is created.
	 */
	characteristicCategories?: ISAMaterialAttributeSchema1[];
	/**
	 * List of all the units defined in the study, used to avoid duplication of their declaration when each value is created.
	 */
	unitCategories?: ISAOntologyReferenceSchema[];
	processSequence?: ISAProcessOrProtocolApplicationSchemaCorrespondsToProtocolREFColumnsInTheStudyAndAssayFiles[];
	comments?: ISACommentSchemaItCorrespondsToISACommentConstruct[];
}
